apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-prometheus
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dmitry/GeekBrains/4_Semestr/practice/1_conteinerization/lesson_07/my_pv
  storageClassName: local
